### PR TITLE
Add markdown editing for game reviews.

### PR DESCRIPTION
**Pull request by sergiotapia**
This allows users to write and render their reviews using markdown. ~~I still need to fix a UI hiccup with the markdown editor toolbar.~~

This pull request is ready ship! :rocket:

### CODE REVIEW

**Comment by Lockyy** [comment]
This looks great, just a few things that need changing. 

* The textarea needs some padding on all sides so the text doesn't press up against the edges;
* Add some margin below the textarea so it doesn't press up against the button;
* and disable images and links, we don't want spammers or trolls abusing the system.

**Comment by sergiotapia** [comment]
Sounds good, I'll tweak it.

**Comment by sergiotapia** [comment]
:rocket: All set @Lockyy

**Comment by tjhorner** [comment]
@Lockyy Question: why should we disable links? People can still write links in their review without the button, if you don't want them you can make the Markdown processor add `rel="nofollow"` to them.

**Pull request merged**
