### PR TITLE
Add ruby gemset and version configuration to project.

### PR DESCRIPTION
**Pull request by sergiotapia**
This allows contributors to be using the same Ruby version and keep dependencies installed to the same gemset.

### CODE REVIEW

**Comment by Ruxton** [comment]
:+1: though it shouldn't need to be declared in the Gemfile.

**Comment by sergiotapia** [comment]
Is there a better alternative? This article gives the impression that it's either done through the Gemfile or the ENV variables.

https://devcenter.heroku.com/articles/ruby-versions

**Comment by Lockyy** [comment]
Merged in on command line, little bit of messy history sorry.

**Comment by sergiotapia** [comment]
No problemo :rocket:

**Pull request closed without merging**
